pipeline {
    agent {
        label 'master'
    }
    stages {
        stage('Test') {
            agent {
                docker {
                    image 'cloudfluff/csvlint'
                    reuseNode true
                    alwaysPull true
                }
            }
            steps {
                script {
                    ansiColor('xterm') {
                        sh "csvlint -s reference/codelists-metadata.json"
                        sh "csvlint -s reference/columns.csv-metadata.json"
                        sh "csvlint reference/components.csv"
                    }
                }
            }
        }
        stage('Upload') {
            steps {
                script {
                    jobDraft.replace()
                    def codelists = readJSON(file: 'reference/codelists-metadata.json')
                    for (def table : codelists['tables']) {
                        String codelistFilename = table['url']
                        String label = table['rdfs:label']
                        uploadCodelist("reference/${codelistFilename}", label)
                    }
                    uploadComponents("reference/components.csv")
                }
            }
        }
        stage('Publish') {
            steps {
                script {
                    jobDraft.publish()
                }
            }
        }
    }
}
